#!/bin/bash
SAVE_PATH="$HOME/Pictures/Screenshots"
FILE_NAME="Screenshot-$(date +%Y-%m-%d_%H-%M-%S).png"
FILE_PATH="$SAVE_PATH/$FILE_NAME"

TOOL="deepin-screenshot" #"gnome-screenshot"
FLAG_WINDOW="" #"-w"
FLAG_AREA="" #"-a"
FLAG_FULL="-f" #""
FLAG_PATH="-s" #"-f"

COMMAND="$TOOL --no-notification $FLAG_PATH \"$FILE_PATH\""
if [ ! -d "$SAVE_PATH" ]; then
    mkdir -p "$SAVE_PATH"
fi

if [[ "$#" -eq 1 ]]; then
    if [[ $1 == "-a" || $1 == "-ar"* || $1 == "-reg"* ]]; then
        COMMAND="$COMMAND $FLAG_AREA"
    elif [[ $1 == "-w"* ]]; then
        COMMAND="$COMMAND $FLAG_WINDOW"
    else
        COMMAND="$COMMAND $FLAG_FULL"
    fi
else
    COMMAND="$COMMAND $FLAG_FULL"
fi

eval $COMMAND
xupload "$FILE_PATH"
